version: "3.8"

services:
  web:
    build:
      context: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - feedback_network

  db:
    image: postgres:14
    env_file:
      - .env  # Load environment variables for PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - feedback_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - feedback_network

volumes:
  postgres_data:  # Define the named volume

networks:
  feedback_network:  # Define a custom network
    name: feedback_system_network
