# Generated by Django 5.1.4 on 2024-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_feedback_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
