# Generated by Django 5.1.4 on 2024-12-27 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_chathistory_rating_delete_userinteraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='feedback.feedback'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='chat_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='feedback.chathistory'),
        ),
    ]
