name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest

      - name: Stop Existing Container
        run: docker stop feedback_system || true && docker rm feedback_system || true

      - name: Run Latest Container
        run: |
          docker run -d \
            --name feedback_system \
            -p 8000:8000 \
            --env-file .env \
            ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest
