name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest
          docker stop feedback_container || true
          docker rm feedback_container || true
          docker run -d -p 8000:8000 --name feedback_container ${{ secrets.DOCKERHUB_USERNAME }}/feedback_system:latest
